workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
  - test

build:
  stage: build
  script:
    - composer install

test:
  stage: test
  script:
    - composer test
